/*
 * This file is generated by jOOQ.
 */
package com.example.snowalkershardingjdbcdemo.sjb.repos.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrder implements Serializable {

    private static final long serialVersionUID = -737466879;

    private Integer id;
    private Long    userId;
    private Long    orderId;
    private String  userName;

    public TOrder() {}

    public TOrder(TOrder value) {
        this.id = value.id;
        this.userId = value.userId;
        this.orderId = value.orderId;
        this.userName = value.userName;
    }

    public TOrder(
        Integer id,
        Long    userId,
        Long    orderId,
        String  userName
    ) {
        this.id = id;
        this.userId = userId;
        this.orderId = orderId;
        this.userName = userName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TOrder (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(orderId);
        sb.append(", ").append(userName);

        sb.append(")");
        return sb.toString();
    }
}
