info:
  app:
    name: Consumer Service
    description: Leo消费者服务

server:
  #servlet:
  #  定义项目的访问访问路径
  #context-path: /
  #定义端口号
  port: 7001

spring:
  application:
    name: consumer
  security:
    user:
      name: root
      password: root
  rabbitmq:
    host: 10.200.23.67
    port: 5672
    username: admin
    password: admin
    #publisher-confirms: true   #消息发送到交换机确认机制,是否确认回调
    publisher-confirm-type: correlated #消息发送到交换机确认机制,是否确认回调
    listener:
      simple:
        acknowledge-mode: manual #ACK手动确认
  datasource:
      #url: jdbc:mysql://localhost:3306/easybuy_bfs?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      #username: root
      #password: root
      #url: jdbc:mysql://easybuycore-test.c5mhjt483svq.us-west-2.rds.amazonaws.com:3306/easybuy_bfs?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      #username: prodeasybuycore
      #password: prodeasybuycore!!##!!$$
      url: jdbc:mysql://easybuycore-reader-1.cluster-custom-c0v0yilplr53.eu-west-1.rds.amazonaws.com:3306/easybuy_bfs?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: user-ro
      password: prodeasybuycore-ro!!!!
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.leo.**.entity
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #关键部分。用来显示sql

#默认超时时间1s
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka


