info:
  app:
    name: Product Service
    description: Leo产品服务

spring:
  application:
    name: product
  datasource:
    #url: jdbc:mysql://localhost:3306/easybuy_bfs?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    #username: root
    #password: root
    #url: jdbc:mysql://easybuycore-test.c5mhjt483svq.us-west-2.rds.amazonaws.com:3306/easybuy_bfs?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    #username: prodeasybuycore
    #password: prodeasybuycore!!##!!$$
    url: jdbc:mysql://easybuycore-reader-1.cluster-custom-c0v0yilplr53.eu-west-1.rds.amazonaws.com:3306/easybuy_bfs?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: user-ro
    password: prodeasybuycore-ro!!!!
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 7002
  #servlet:
    #context-path: /

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.leo.**.entity
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #关键部分。用来显示sql

eureka:
  client:
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      defaultZone: http://localhost:7070/eureka