/*
 * This file is generated by jOOQ.
 */
package com.example.snowalkershardingjdbcdemo.sjb.repos;


import com.example.snowalkershardingjdbcdemo.sjb.repos.tables.TOrder;
import com.example.snowalkershardingjdbcdemo.sjb.repos.tables.records.TOrderRecord;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TOrderRecord, Integer> IDENTITY_T_ORDER = Identities0.IDENTITY_T_ORDER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TOrderRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TOrderRecord, Integer> IDENTITY_T_ORDER = Internal.createIdentity(TOrder.T_ORDER, TOrder.T_ORDER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<TOrderRecord> CONSTRAINT_A = Internal.createUniqueKey(TOrder.T_ORDER, "CONSTRAINT_A", TOrder.T_ORDER.ID);
    }
}
